### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "asdf2@asdf.com",
    "password": "asdfgh",
    "trash": 1231
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1


### Find all users with a given email
GET http://localhost:3000/auth?email=asdf2@asdf.com


### Delete a user with a given id
DELETE  http://localhost:3000/auth/2

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email": "fdsa@asdf.com"
}