### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "newuseraftercookie2@asdf.com",
    "password": "asdfgdh",
    "trash": 999
}


### Sign in
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "newuseraftercookie@asdf.com",
    "password": "asdfgdh",
    "trash": 999
}



### Find a particular user with a given ID
GET http://localhost:3000/auth/1


### Find a particular user with a given ID
GET http://localhost:3000/auth/whoami


### Find all users with a given email
GET http://localhost:3000/auth?email=asdf2@asdf.com


### Delete a user with a given id
DELETE  http://localhost:3000/auth/5

### Update a user
PATCH http://localhost:3000/auth/3
content-type: application/json

{
    "email": "fdsa@asdf.com"
}